---
swagger: "2.0"
info:
  description: "Aims Quant api publisher"
  version: "1.0.0"
  title: "AimsQuant api"
  termsOfService: "http://aimsquant.io/terms/"
  contact:
    email: "shiv@aimsquant.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8000"
basePath: "/api/v2"
tags:
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about us"
    url: "http://aimsquant.io"
schemes:
- "http"
paths:
  /user:
    post:
      tags:
      - "user"
      summary: "Register user"
      description: "User registration api."
      operationId: "regiteruser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
      x-swagger-router-controller: "User"
  /user/login:
    post:
      tags:
      - "user"
      summary: "User Login"
      description: "User login for all roles. If project_admin tenantName is not required"
      operationId: "userlogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User login description. Check model definition for valid params"
        required: true
        schema:
          $ref: "#/definitions/Login"
      responses:
        200:
          description: "successful login"
        400:
          description: "Not Authorized"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "User"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
      x-swagger-router-controller: "User"
definitions:
  User:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      photo:
        type: "string"
      aboutme:
        type: "string"
      education:
        type: "string"
      profession:
        type: "string"
  Login:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
  Error:
    type: "object"
    properties:
      code:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
